studentName: "Segueda-Esdras-Harold"

replicaCount: 3

image:
  repository: harold78/app-harold
  tag: "0941721"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  targetPort: 5000
  nodePort: 30080

resources:
  limits:
    cpu: "500m"
    memory: "256Mi"
  requests:
    cpu: "250m"
    memory: "128Mi"
