apiVersion: v1
kind: Service
metadata:
  name: app-harold-service
spec:
  type: NodePort
  selector:
    app: app-harold
  ports:
    - protocol: TCP
      port: 80         # Le port exposé à l'intérieur du cluster
      targetPort: 5000 # Le port sur lequel écoute ton application Flask
      nodePort: 30080  # Le port externe accessible depuis ton navigateur
